In [1]:
import pandas as pd

In [2]:
#Read csv files
df_uniques = pd.read_csv("DEFINITIVE_TABLES/DIAGS_UNIQUE_ROW.csv")
df_uniques["NATIONALITY"] = df_uniques["NATIONALITY"].apply(lambda x : "Local" if x == "Israeli" else "Foreigner")
df_uniques.drop(["SWITCHDATE", "HOSPITAL", "DOCTOR", "SPECIALITY"], axis = 1, inplace = True)
df_uniques["DISEASE"] = df_uniques["DISEASE"].replace("No Diseases", float("NaN"))

In [10]:
df_uniques["COUNT"] = df_uniques.groupby('ID').size()
df_uniques

,GENDER,ID,YEAR,NATIONALITY,REGION,AGE_GROUP,DISEASE,COUNT
0,Female,Patient_10000032_1,1972,Local,Al Dhafra,50-59,Nash,NaN
1,Female,Patient_10000048_1,2001,Local,Abu Dhabi,20-29,NaN,NaN
2,Female,Patient_10000068_1,2005,Local,Al Ain,10-19,NaN,NaN
3,Male,Patient_10000084_1,1952,Local,Al Ain,70+,Dyslipidemia,NaN
4,Female,Patient_10000102_1,1997,Local,Abu Dhabi,20-29,NaN,NaN
...,...,...,...,...,...,...,...,...
426797,Female,Patient_19999829_1,1996,Local,Al Ain,20-29,NaN,NaN
426798,Male,Patient_19999840_1,1966,Local,Abu Dhabi,50-59,Heart disease,NaN
426799,Female,Patient_19999914_1,1975,Local,Al Dhafra,40-49,NaN,NaN
426800,Female,Patient_19999987_1,1967,Foreigner,Al Ain,50-59,Heart disease,NaN
426801,Female,Patient_19999987_1,1967,Foreigner,Al Ain,50-59,CKD,NaN

In [40]:
disease_count_per_id = pd.DataFrame(pd.DataFrame(df_uniques[df_uniques["DISEASE"] != "No Diseases"].groupby('ID')['DISEASE'].count()).reset_index()["DISEASE"].value_counts()).reset_index()

In [41]:
disease_count_per_id

   DISEASE   count
0        0  201309
1        1   38081
2        2   24566
3        3   16167
4        4   11028
5        5    6011
6        6    2238
7        7     312

In [16]:
df_uniques[df_uniques["DISEASE"] == "No Diseases"]

,GENDER,ID,YEAR,NATIONALITY,REGION,AGE_GROUP,DISEASE
1,Female,Patient_10000048_1,2001,Local,Abu Dhabi,20-29,No Diseases
2,Female,Patient_10000068_1,2005,Local,Al Ain,10-19,No Diseases
4,Female,Patient_10000102_1,1997,Local,Abu Dhabi,20-29,No Diseases
5,Male,Patient_10000108_1,1999,Local,Al Ain,20-29,No Diseases
6,Male,Patient_10000115_1,2000,Local,Abu Dhabi,20-29,No Diseases
...,...,...,...,...,...,...,...
426793,Male,Patient_19999750_1,1979,Local,Abu Dhabi,40-49,No Diseases
426794,Female,Patient_19999782_1,2002,Local,Al Ain,20-29,No Diseases
426795,Male,Patient_19999784_1,1967,Local,Abu Dhabi,50-59,No Diseases
426797,Female,Patient_19999829_1,1996,Local,Al Ain,20-29,No Diseases
426799,Female,Patient_19999914_1,1975,Local,Al Dhafra,40-49,No Diseases

In [12]:
a=df_uniques[df_uniques["DISEASE"] == "CKD"].groupby(['GENDER', 'AGE_GROUP']).size().reset_index()
a.columns = ["GENDER", "AGE_GROUP", "COUNT"]

In [21]:
import pandas as pd
import altair as alt

# Sample data
data = pd.DataFrame({
    'category': ['MALE', 'MALE', 'MALE', 'MALE', 'FEMALE', 'FEMALE'],
    'subcategory': ['10-19', '20-29', '30-39', '40-49', '50-59', '60-69'],
    'value': [10, 20, 30, 40, 50, 60]
})

# Creating a tree map with a hot scale color
tree_map = alt.Chart(a).mark_rect().encode(
    y=alt.Y('GENDER:N', title='Category'),
    x=alt.X('AGE_GROUP:N', title='Subcategory'),
    color=alt.Color('COUNT:Q', scale=alt.Scale(scheme='reds'), title='Count'),
    size='COUNT:Q').properties(
    width=500,
    height=150,
)

tree_map

alt.Chart(...)

In [21]:
import pandas as pd

# Creating DataFrame for Disease Cases
df_disease_cases = pd.DataFrame({
    'Disease': ['Diabetes', 'Heart Disease', 'Dyslipidemia', 'Nash', 'CKD', 'Hypertension'],
    'Gender': ['Male', 'Male', 'Female', 'Female', 'Male', 'Female'],
    'Cases': [30000, 28000, 15000, 13000, 8500, 3650]
})

# Creating DataFrame for Disease Speciality
df_disease_speciality = pd.DataFrame({
    'Disease': ['Diabetes', 'Heart Disease', 'Dyslipidemia', 'Nash', 'CKD', 'Obesity'],
    'Speciality': ['Endocrinology', 'Cardiology', 'Endocrinology', 'Hepatology', 'Nephrology', 'Bariatric']
})

df_disease_speciality

         Disease     Speciality
0       Diabetes  Endocrinology
1  Heart Disease     Cardiology
2   Dyslipidemia  Endocrinology
3           Nash     Hepatology
4            CKD     Nephrology
5        Obesity      Bariatric

In [20]:
df_disease_cases

         Disease  Gender  Cases
0       Diabetes    Male  30000
1  Heart Disease    Male  28000
2   Dyslipidemia  Female  15000
3           Nash  Female  13000
4            CKD    Male   8500
5   Hypertension  Female   3650

In [29]:
# Performing an inner join on the two dataframes based on the 'Disease' column
merged_df = pd.merge(df_disease_cases, df_disease_speciality, on='Disease', how='outer')
merged_df

         Disease  Gender    Cases     Speciality
0       Diabetes    Male  30000.0  Endocrinology
1  Heart Disease    Male  28000.0     Cardiology
2   Dyslipidemia  Female  15000.0  Endocrinology
3           Nash  Female  13000.0     Hepatology
4            CKD    Male   8500.0     Nephrology
5   Hypertension  Female   3650.0            NaN
6        Obesity     NaN      NaN      Bariatric

In [ ]:
# We create the directed graph
G = nx.DiGraph()
# Add nodes and directed edges to the graph
for _, row in rules1.iterrows():
    for antecedent in row['antecedents']:
        for consequent in row['consequents']:
            G.add_edge(antecedent, consequent, weight=row['lift'])

# Draw the graph
plt.figure(figsize=(15, 8))
pos = nx.spring_layout(G, k=0.5, iterations=50)
weights = [G[u][v]['weight'] for u, v in G.edges()]

# Draw nodes and labels
nx.draw_networkx_nodes(G, pos, node_size=5000, node_color='lightblue')
nx.draw_networkx_labels(G, pos, font_size=10, font_weight='bold')

# Draw directed edges and weight labels
edges = nx.draw_networkx_edges(G, pos, arrowstyle='-|>', arrowsize=20, edge_color=weights, width=2.0, edge_cmap=plt.cm.Blues)
edge_labels = nx.get_edge_attributes(G, 'weight')
nx.draw_networkx_edge_labels(G, pos, edge_labels={(u, v): f'{d:.2f}' for (u, v), d in edge_labels.items()})

# Add colorbar
sm = plt.cm.ScalarMappable(cmap=plt.cm.Blues, norm=plt.Normalize(vmin=min(weights), vmax=max(weights)))
sm.set_array([])
plt.colorbar(sm, label='Lift')

plt.title('Directed Association Rules Graph')
plt.show()

In [27]:
df_uniques = pd.read_csv("DEFINITIVE_TABLES/COMBINATIONS.csv")

In [91]:
df_uniques['COUNTS'] = df_uniques['COMBINED_DIAGS'].apply(lambda x: len(x.split(',')))
df_uniques.loc[df_uniques['COMBINED_DIAGS'] == 'No diags', 'COUNTS'] = 0
df_uniques["COUNTS"] = df_uniques["COUNTS"].apply(lambda x : "+3" if x > 3 else x)
counts_combis = pd.DataFrame(df_uniques.groupby('COUNTS').size().reset_index())
counts_combis.columns = ["COMBINATIONS", "COUNTS"]
total_counts = counts_combis['COUNTS'].sum()
counts_combis['PERCENTAGE'] = (counts_combis['COUNTS'] / total_counts)

# Calculate the cumulative counts and positions
counts_combis['POSITION'] = 0
for i in range(len(counts_combis)):
    if i == 0:
        counts_combis.loc[i, 'POSITION'] = counts_combis.loc[i, 'COUNTS'] / 2
    else:
        counts_combis.loc[i, 'POSITION'] = counts_combis.loc[i - 1, 'POSITION'] + counts_combis.loc[i-1, 'COUNTS'] / 2 + counts_combis.loc[i, 'COUNTS'] / 2

In [92]:
counts_combis

  COMBINATIONS  COUNTS  PERCENTAGE  POSITION
0            0  201310    0.671678  100655.0
1            1   38081    0.127059  220350.5
2            2   24566    0.081965  251674.0
3            3   16167    0.053942  272040.5
4           +3   19588    0.065356  289918.0

In [53]:
import altair as alt

In [111]:
# Prepare data for stacked bar chart
combis_chart = alt.Chart(counts_combis).mark_bar().encode(
            x = "COUNTS",
            color='COMBINATIONS:N'
            ).properties(
            height=150,
            width='container'
        )

text =  alt.Chart(counts_combis).mark_text(align='center', baseline='middle', color="white", fontWeight='bold', fontSize=16).encode(
            text=alt.Text('PERCENTAGE:Q', format='.2%'), x="POSITION:Q"
        )
combis_chart + text

alt.LayerChart(...)

alt.LayerChart(...)

In [78]:
text

alt.Chart(...)

In [80]:
counts_combis

  COMBINATIONS  COUNTS  PERCENTAGE
0            0  201310    0.671678
1            1   38081    0.127059
2            2   24566    0.081965
3            3   16167    0.053942
4           +3   19588    0.065356

In [105]:
df_combinations = pd.read_csv("DEFINITIVE_TABLES/COMBINATIONS.csv")

In [106]:
df_combinations['COUNTS'] = df_combinations['COMBINED_DIAGS'].apply(lambda x: len(x.split(',')))
df_combinations.loc[df_combinations['COMBINED_DIAGS'] == 'No diags', 'COUNTS'] = 0
df_combinations["COUNTS"] = df_combinations["COUNTS"].apply(lambda x : "+3" if x > 3 else x)
counts_combis = pd.DataFrame(df_combinations.groupby('COUNTS').size().reset_index())
counts_combis.columns = ["COMBINATIONS", "COUNTS"]
total_counts = counts_combis['COUNTS'].sum()
counts_combis['PERCENTAGE'] = (counts_combis['COUNTS'] / total_counts)

# Calculate the cumulative counts and positions
counts_combis['POSITION'] = 0
for i in range(len(counts_combis)):
    if i == 0:
        counts_combis.loc[i, 'POSITION'] = counts_combis.loc[i, 'COUNTS'] / 2
    else:
        counts_combis.loc[i, 'POSITION'] = counts_combis.loc[i - 1, 'POSITION'] + counts_combis.loc[i-1, 'COUNTS'] / 2 + counts_combis.loc[i, 'COUNTS'] / 2

In [115]:
combis_chart = alt.Chart(counts_combis).mark_bar().encode(
            x=alt.X('COUNTS'),
            color=alt.Color('COMBINATIONS:N')
            ).properties(
            height=150,
        )

text =  alt.Chart(counts_combis).mark_text(align='center', baseline='middle', color="white", fontWeight='bold', fontSize=16).encode(
            text=alt.Text('PERCENTAGE:Q', format='.2%'), x="POSITION:Q"
        )

In [116]:
combis_chart + text

alt.LayerChart(...)

In [114]:
counts_combis

  COMBINATIONS  COUNTS  PERCENTAGE  POSITION
0            0  201310    0.671678  100655.0
1            1   38081    0.127059  220350.5
2            2   24566    0.081965  251674.0
3            3   16167    0.053942  272040.5
4           +3   19588    0.065356  289918.0